package objects;

import util.converters.LengthConverter;
import util.converters.PressureConverter;

public class Railgun {
	static class Variables {
		/**
		 * The length of the railgun in feet
		 */
		static double length;
		
		/**
		 * The length of the railgun in meters
		 */
		static double lengthM;
		
		/**
		 * The distance between the railgun rails in inches
		 */
		static double distBetweenRails;
		
		/**
		 * The distance between the railgun rails in meters
		 */
		static double distBetweenRailsM;
		
		/**
		 * The angle of launch in degrees
		 */
		static double angleOfLaunch;
		
		/**
		 * The angle of launch in radians
		 */
		static double angleOfLaunchR;
		
		/**
		 * The air pressure behind the projectile in PSI
		 */
		static double airPressurePSI;
		
		/**
		 * The air pressure behind the projectile in N/m^2
		 */
		static double airPressureN;
		
		/**
		 * The force generated by the Lorentz Force in Newtons
		 */
		static double lorentzForce;
	}
	
	/**
	 * 
	 * @param l
	 * @param d
	 * @param a
	 */
	public Railgun(double l, double d, double a, double lF) {
		Variables.length = l; Variables.distBetweenRails = d; Variables.angleOfLaunch = a; init(); Variables.lorentzForce = lF;
	}
	
	static void init() {
		Variables.lengthM = LengthConverter.convertToMeters(Variables.length, "ft");
		Variables.distBetweenRailsM = LengthConverter.convertToMeters(Variables.distBetweenRails, "in");
		Variables.angleOfLaunchR = Math.toRadians(Variables.angleOfLaunch);
		Variables.airPressureN = PressureConverter.convertToPascals(Variables.airPressurePSI, "psi");
	}
}
